# Generated by Django 4.2.2 on 2023-07-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_sharing_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_file',
            field=models.FileField(default='', upload_to='note/'),
        ),
    ]
