# Generated by Django 4.2.2 on 2023-07-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_sharing_app', '0002_note_note_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='media/')),
            ],
        ),
    ]
